### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by Pacodastre** [fox-it/django-auth-policy#14]
The package as distributed contains a few typos. Here is a patch to fix them: https://gist.github.com/Pacodastre/611c0be2ffa03cf4b845

(I forked the repo, but it's not on github, so I can not submit a pull request)

**Comment by ronaldevers** [comment]
Hi Padocastre, thanks for your patches. We can review them here but it is probably better to submit them to this fork: https://github.com/rudolphfroger/django-auth-policy. That fork is much more recent and maintained than ours. Thanks again!
